version: "3.9"

services:
  backend:
    build: ./server
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env.production
    command: npm start
    networks:
      - app-network

  frontend:
    build: ./client
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
