version: "3.9"

services:
  backend:
    build: ./server
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm start
    env_file:
      - ./server/.env.development
    networks:
      - app-network

  frontend:
    build: ./client
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
