version: "3.8"
services:
  backend:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  frontend:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - backend
