version: "3.9"

services:
  backend:
    build: ./server
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm start
    env_file:
      - ./server/.env.development
    networks:
      - app-network

 frontend:
  build: ./client
  ports:
    - "5173:5173"
  volumes:
    - ./client:/app
    - /app/node_modules
  command: npm run dev -- --host
  depends_on:
    - backend
  networks:
    - app-network
