version: '3.8'

services:
  backend:
    container_name: guitarshop-backend
    image: phuonglam2507/guitarshop-backend:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
    restart: always

  frontend:
    container_name: guitarshop-frontend
    image: phuonglam2507/guitarshop-frontend:latest
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - backend
    restart: always
