version: "3.9"

services:
  backend:
    image: docker.io/<DOCKERHUB_USER>/server-app:latest
    container_name: giutar_server
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env

  frontend:
    image: docker.io/<DOCKERHUB_USER>/client-app:latest
    container_name: giutar_client
    restart: always
    ports:
      - "80:80"

networks:
  default:
    driver: bridge
