name: Build and Push Frontend Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
      # 1. Lấy code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Đăng nhập Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build image frontend (React hoặc Vite)
      - name: Build Frontend Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/guitarshop-frontend:latest ./client

      # 4. Push image lên Docker Hub
      - name: Push Frontend Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/guitarshop-frontend:latest
